name: Artifacts
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Show workspace path
        run: echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      - name: Create date file
        run: date > date.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
          retention-days: 7
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - name: Show workspace path
        run: echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: uploaded
          path: downloaded
      - name: Show file content
        run: cat downloaded/date.txt