name: Artifacts
on: push
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_WORKSPACE: ${{ GITHUB_WORKSPACE }}"
      - run: date > date.txt
      - uses: actions/upload-artifact@v4
        with:
          name: uploaded
          path: date.txt
          retention-days: 7
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    steps:
      - run: echo "GITHUB_WORKSPACE: ${{ GITHUB_WORKSPACE }}"
      - uses: actions/download-artifact@v4
        with:
          name: uploaded
          path: downloaded
      - run: cat downloaded/date.txt