name: Bash tracing
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.actor }}
    steps:
      - run: |
          echo "::warning::This is a warning"
          echo "## Example of a masked variable"
          echo "- HOME:">> " $HOME"
          echo "::add-mask::${USERNAME}"
          echo "USERNAME: $USERNAME"
          echo "USER: $USER"
          echo "PWD: $PWD"
          echo "::endgroup::"

      - run: |
          set -x
          date
          hostname
        