name: Bash tracing
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Show environment variables"
          echo "USERNAME: $USERNAME"
          echo "USER: $USER"
          echo "HOME: $HOME"
          echo "PWD: $PWD"
          echo "::endgroup::"

      - run: |
          set -x
          date
          hostname
        