name: Environments
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: test
        required: false
        description: "The environment to deploy to"
jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" 
