name: Manual Matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version: 20
          - os: macos-latest
            version: 18
          - os: windows-latest
            version: 2019
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.version }}
      - run: echo "${RUNNER_OS}" && node --version
        