name: Other

on: push

jobs: 
  print:
    runs-on: ubuntu-latest
    env:
     BRANCH: main
    steps:
      - run: echo "${{ runner.os }}"
      - - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}
